### Chamada GET /api/v1/clientes
GET http://localhost:8081/api/v1/clientes

### Chamada POST /api/v1/clientes
POST http://localhost:8081/api/v1/clientes
Content-Type: application/json

{
    "nome": "Mariazinha da Silva Sauro",
    "endereco": "Rua lulululul 200",
    "dataNascimento": "2024-04-22"
}
### Chamada PUT /api/v1/clientes
PUT http://localhost:8081/api/v1/clientes/1
Content-Type: application/json

{
    "nome": "Zezinho da Silva Sauro JUNIOR",
    "endereco": "Rua lalalala 1000",
    "dataNascimento": "2024-04-25"
}